### PR TITLE
Support Multi-AWS-Account Setup

### PR DESCRIPTION
**Pull request by dav3r**
This PR includes everything that was needed to go from a single (AWS) account setup, to our more modern multi-account setup.

I also took some time to enhance and clean up the README.

### CODE REVIEW

**Review by felddy — APPROVED** [review]
You're touring the facilities and picking up slack!  
Well done!

**Review by jsf9k — APPROVED** [review]
I like this.

Do we want to add the "Setting up the Terraform AWS S3 backend" blurb (or anything else) to skeleton-tf-module?  I have the feeling there are some pieces here that are going to get repeated a lot going forward.

**Comment by dav3r** [comment]
Good thinking @jsf9k, I will add that blurb to the skeleton-tf-module.

**Comment by dav3r** [comment]
So it turns out that [skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module) doesn't actually have a `terraform.tf` file, so I'm not sure it makes sense to add this particular blurb.  Maybe it's time for a `skeleton-terraform` repo, which could be a base for repos like [pca-terraform](https://github.com/cisagov/pca-terraform) and [rva-terraform](https://github.com/cisagov/rva-terraform)?

**Comment by jsf9k** [comment]
> Maybe it's time for a `skeleton-terraform` repo, which could be a base for repos like [pca-terraform](https://github.com/cisagov/pca-terraform) and [rva-terraform](https://github.com/cisagov/rva-terraform)?

If you think you have a good enough understanding to create such a thing then go for it.  I'm not there yet.

**Review by mcdonnnj — APPROVED** [review]
Helping us live our best multi-account life. 👍

**Pull request merged**
